### PR TITLE
Linux GUI with GTK

### PR DESCRIPTION
**Pull request by MrLoLf**
This should work on most Linux distros, and maybe even on Windows, if you set it up for it. It detects the files and works as intended, as far as I have tested it. It uses .net7.0 and GTK 3.

### CODE REVIEW

**Comment by eitambelahousky** [comment]
Thanks for your PR!
Seeing lots of styling changes which are irrelevant. Can you make sure the PR includes only the changes relevant for the Linux GUI?
Thanks

**Comment by MrLoLf** [comment]
I have done my best on avoiding style changes by copying the old files now and replacing them with the Rider formatted ones. But some are still marked as being changed, but there are no changes made. My changes are all in the DetectionToolLinux and in the DetectionTool.sln, as I've added the directory to the project and DetectionTool.sln.DotSettings.user this file got autogenerated from Rider.

This is how the GUI Looks like.
image

**Comment by eitambelahousky** [comment]
Thanks! Still some files which seem irrelevant. I added the Linux project you created to the solution and opened a new PR

https://github.com/overwolf/detection-tool/pull/16

**Comment by MrLoLf** [comment]
Alright I'll close this PR than now.

**Pull request closed without merging**
